### ISSUE TITLE
Release version with GHC 8.8 support

### ISSUE THREAD

**Issue by bravit** [diagrams/diagrams-cairo#75] opened 2019-12-16 11:18 UTC
It seems that `master` can be built now with GHC 8.8 despite CI issues. Could you please release it?

**Comment by byorgey** [comment] 2019-12-16 11:29
Really?  I can't build it with GHC 8.8 on my machine.  I get errors similar to those visible in CI---something about `invalid use of ‘__builtin_va_arg_pack ()’` while building `glib`.  How did you get it to build?

**Comment by bravit** [comment] 2019-12-16 11:36
Interesting, I've just installed `pkg-config`, `cairo`, and `pango` on an almost fresh machine with macOS Catalina and everything runs smoothly. I thought it's just some CI stuff.

**Comment by fryguybob** [comment] 2019-12-16 15:31
I just tried and I can reproduce the `__builtin_va_arg_pack ()` error locally on Ubuntu 18.04.  I'll see what I can track down.

**Comment by fryguybob** [comment] 2019-12-16 15:49
I can successfully build `glib` if I add `-D_FORTIFY_SOURCE=0` to the `cpp-options` in the `.cabal` file.

**Comment by fryguybob** [comment] 2019-12-16 16:19
I finally found how to make `cabal v2-install` do what I want and I can confirm that `diagrams-cabal` builds and works using the `glib` built with the flag I mention above.

It isn't clear to me who's problem this is, `gtk2hs` or `gcc` or `ghc` or `cabal` what the scope is (fixed in some version of `gcc`?  Only linux?).  My guess is at some point `gcc` changed a default (`gnu11` instead of `gnu89` perhaps?) and this increased the checking of use of variable argument functions.  These checks are conservative and `glib` itself does not pass them.  `gtk2hs`'s `glib` project is using these headers which get checked and fail to pass.  I don't know what changed with `ghc` or `cabal` to allow the combination of flags that leads to the problem.

**Comment by byorgey** [comment] 2019-12-16 22:32
@fryguybob So are you saying this is something we can work around by putting this flag in our `.cabal` file?  Or is it something where users will have to use the right magic incantation when building?

**Comment by fryguybob** [comment] 2019-12-17 04:34
@byorgey It looks like there was as a recent change to `glib` that might be responsible:

https://github.com/gtk2hs/gtk2hs/commit/4bb428e144ef2de9390f0f2239dcc50b7fc9a259

His the suspiciously broad flag `-D__attribute__(A)=`.  There is a pull request right now to change this and more directly address the underlying issue:

https://github.com/gtk2hs/gtk2hs/issues/276

The change in this pull request also appears to fix building `glib` for me:

https://github.com/gtk2hs/gtk2hs/pull/289

Constraining to `glib-0.13.7.0` might work, but I haven't had success with that locally.

**Comment by fryguybob** [comment] 2019-12-17 13:43
I don't know how helpful this is, but this succeeded on my system:

```
$ cabal new-install glib-0.13.7.0 --lib --allow-newer
```

**Comment by byorgey** [comment] 2020-01-11 17:25
The newest release of `gtk2hs` fixed the issue for me, so (after dropping support for GHC 7.10 and 8.0) I went ahead and released `diagrams-cairo-1.4.1.1` to Hackage.

**Closed by byorgey** 2020-01-11 17:25 UTC
